/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.renren.web.action;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.renren.domain.Users;
import com.renren.service.inter.UserServiceInter;
import com.renren.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-19-2016
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" parameter="flag" scope="request" validate="true"
 */
public class LoginAction extends DispatchAction {
	@Resource
	private UserServiceInter userService;
    public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}
	//用户登录
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		Users user = new Users();
		user.setEmail(userForm.getEmail());
		user.setPwd(userForm.getPwd());
		System.out.println("name and pwd:"+user.getEmail()+"--"+user.getPwd());
		user = userService.check(user);
		if(user != null){
			//用户合法，将用户信息放入session中
			request.getSession().setAttribute("loginuser", user);
			return mapping.findForward("goHome");
		}else{
			return mapping.findForward("goBackIndex");
		}
	}
	//用户注销
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		   request.getSession().invalidate();
		   return mapping.findForward("goBackIndex");
	}
}