/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.renren.web.action;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import com.renren.domain.Users;
import com.renren.service.inter.UserServiceInter;
import com.renren.struts.form.UserForm;
import com.renren.util.MyTools;

/** 
 * MyEclipse Struts
 * Creation date: 04-19-2016
 * 
 * XDoclet definition:
 * @struts.action parameter="flag" validate="true"
 */
public class ProfileAction extends DispatchAction {
	
	@Resource
	private UserServiceInter userService;
    public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}
    
	//跳转到个人主页
	public ActionForward goHomePageUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goHomePageUi");
	}
	//跳转到上传图片的页面
	public ActionForward uploadPhotoUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goUpdatePhotoUi");
	}
	//真正上传用户头像
	public ActionForward uploadPhoto(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		UserForm userForm = (UserForm) form;
		FormFile headphoto = userForm.getHeadphoto();
		//把头像传到服务器的某个目录下
		
		Users loginUser = (Users) request.getSession().getAttribute("loginuser");
		
		String newHeadPhoto = MyTools.uploadHead(request, headphoto, String.valueOf(loginUser.getId()));
		System.out.println("formfile.getFileName():"+headphoto.getFileName());		
		loginUser.setPhoto(newHeadPhoto);
		
		userService.update(loginUser);
		
		return mapping.findForward("goUpdatePhotoUi");
	}
}