/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.renren.web.action;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.renren.domain.University;
import com.renren.domain.Users;
import com.renren.domain.Useruniversity;
import com.renren.service.impl.CountryServiceImpl;
import com.renren.service.impl.UniversityServiceImpl;
import com.renren.service.inter.CountryServiceInter;
import com.renren.service.inter.ProvinceServiceInter;
import com.renren.service.inter.UniversityServiceInter;
import com.renren.service.inter.UserServiceInter;
import com.renren.service.inter.UseruniversityServiceInter;
import com.renren.struts.form.UserForm;




public class RegisterAction extends DispatchAction {
	@Resource
	private UserServiceInter userService;
	@Resource 
	private UseruniversityServiceInter useruniversityService;
	@Resource
	private CountryServiceInter countryService;
	@Resource
	private ProvinceServiceInter provinceService;
	@Resource
	private UniversityServiceInter universityservice;
	
	 
	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}

	public void setUseruniversityService(
			UseruniversityServiceInter useruniversityService) {
		this.useruniversityService = useruniversityService;
	}
	
    public void setCountryService(CountryServiceInter countryService) {
		this.countryService = countryService;
	}
   
    
	public void setProvinceService(ProvinceServiceInter provinceService) {
		this.provinceService = provinceService;
	}
	
	
	public void setUniversityservice(UniversityServiceImpl universityservice) {
		this.universityservice = universityservice;
	}

	
	public ActionForward regUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//准备数据，供用户选择大学
		//国家
		request.setAttribute("countrylist", countryService.getResult("from Country", null));
		//省或直辖市
		request.setAttribute("provincelist", provinceService.getResult
							("from Province where country.id=?", new Object[]{new Integer(1)}));
		request.setAttribute("unilist", universityservice.getResult
				("from University where country.id=? and province.id=?", new Object[]{new Integer(1),new Integer(1)}));
		//大学
		
		return mapping.findForward("regui");
	}
	
	//注册用户
	public ActionForward regUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		UserForm userForm = (UserForm)form;
		Users user = new Users();
		user.setEmail(userForm.getEmail());
		user.setLoginDate(new java.sql.Timestamp(System.currentTimeMillis()));
		user.setRegisterDate(new java.sql.Timestamp(System.currentTimeMillis()));
		user.setName(userForm.getName());
		user.setPwd(userForm.getPwd());
		user.setSex(userForm.getSex());
		System.out.println(userForm.getEmail() +"--"+userForm.getPwd()+"--"+userForm.getName()+"--"+userForm.getSex()+"--"+user.getRegisterDate()+"--"+user.getLoginDate());
		//找到用户填写的大学
		University university = (University) universityservice.findById(University.class,Integer.parseInt(userForm.getUniversityId()));
		System.out.println("university:"+university.getName());
		//创建用户大学表对象
		Useruniversity useruniversity = new Useruniversity();
		useruniversity.setUsers(user);
		useruniversity.setUniversity(university);
		useruniversity.setUserType(userForm.getUserType());
		//保存对象
		userService.save(user);
		useruniversityService.save(useruniversity);
		
		return mapping.findForward("regok");
	}
}