/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.renren.web.action;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.stereotype.Controller;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

import com.renren.service.*;



@Controller
public class TestAction extends DispatchAction {
	@Resource
	private TestService testservice; 
	
	public void setTestservice(TestService testservice) {
		this.testservice = testservice;
	}


	public ActionForward showCountry(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		/*WebApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(this.getServlet().getServletContext());
		TestService ts = (TestService) ctx.getBean("testservice");*/
		
		System.out.println("hello");
		List list = testservice.showCountry();
		request.setAttribute("list", list);
		return mapping.findForward("output");
	}
}